### ISSUE TITLE
HTTPS certifcate is expired

### ISSUE THREAD

**Issue by torfsen** [wo-ist-markt/wo-ist-markt.github.io#228]
It seems that our HTTPS certificate expired on September 18, 2017, 1:13 AM. At least that's what my browser tells me. And since we use HSTS I can't access wo-ist-markt.de anymore...

**Comment by MorrisJobke** [comment]
Let me take a look at this

**Comment by MorrisJobke** [comment]
@torfsen Thanks for noticing - the issue is now resolved.

**Comment by MorrisJobke** [comment]
The lets encrypt cron job failed, because one of the earlier hosts in the config had a Nginx config, that didn't served on IPv6. The IPv6 was added to the DNS entry for that domain and Let's Encrypt then preferred that way. Because Nginx didn't served anything for that IP under that domain the verification failed and the cron job stopped. Therefore also all other domains were not renewed. I fixed this and all existing and future Nginx configs are IPv4/6 compatible now.
