### ISSUE TITLE
Display order of days depends on system date

### ISSUE THREAD

**Issue by johnjohndoe** [wo-ist-markt/wo-ist-markt.github.io#303]
The [`Stadtmarkt Basel`](https://github.com/wo-ist-markt/wo-ist-markt.github.io/blob/83036502bd06d9cf2c61df2dc24dd3a887f64785/cities/basel.json?short_path=618fea1#L11-L15) is taken as an example here:

``` json
"opening_hours": "Tu-Th 08:30-14:00;Fr-Sa 08:30-18:00"
```

# How to reproduce
1. Set the system date to Sunday
2. Inspect the market times for the market

# Observed result
- Saturday shows up at the **top** of the list of market times, followed by Tuesday, ...

![Sunday-20190804-basel-market](https://user-images.githubusercontent.com/144518/62421380-0caa7b80-b6a1-11e9-90ea-14f00211d410.png)

# Expected result
- Market times are ordered starting from Tuesday and ending at Saturday.
- Screenshot taken with system date set to Monday.

![Monday-20190805-basel-market](https://user-images.githubusercontent.com/144518/62421381-13d18980-b6a1-11e9-8eaf-ff169be46464.png)

**Comment by ubergesundheit** [comment]
I guess the culprit are lines [177 to 185 in main.js](https://github.com/wo-ist-markt/wo-ist-markt.github.io/blob/master/js/main.js#L177-L185). Especially using `week` instead of `isoweek` in the `startOf` and `endOf` calls seem to produce the issue you described.

`startOf` and `endOf` assume sunday and saturday as start and end of weeks when used with `week`. `isoweek` uses Monday and Sunday.

I only tested with the case you described, because I am unsure why the start and end of week needs to be offset by 1 day.

**Comment by johnjohndoe** [comment]
The particular function has been edited in 76e226a183863591c12ebfefaead3ab2047a0b72 and again in 6e7bb132926ae7282226b98d1fadd514278db387. I hope this gives you some insides. If you like to work on the issue that would be great.
