### ISSUE TITLE
Karlsruhe: Add location for markets

### ISSUE THREAD

**Issue by johnjohndoe** [wo-ist-markt/wo-ist-markt.github.io#52]
I am currently [working on a validation script](https://github.com/wo-ist-markt/wo-ist-markt.github.io/issues/44) for the market data. This identified a few issues for Karlsruhe:

```
KARLSRUHE: Gottesauer Platz
Field 'location' cannot be null.

KARLSRUHE: Gutenbergplatz
Field 'location' cannot be null.

KARLSRUHE: Kronenplatz
Field 'location' cannot be null.

KARLSRUHE: Stephanplatz
Field 'location' cannot be null.

KARLSRUHE: Werderplatz
Field 'location' cannot be null.
```

Can you please update _karlsruhe.json_?

**Comment by torfsen** [comment]
Is there a reason why `location` cannot be `null`? In my understanding it always was an optional field that could be used to specify the precise location in case the (mandatory) `title` was not enough. In the cases you listed the `title` is precise enough, so there's no need for further information.

See also #27.

**Comment by johnjohndoe** [comment]
In an ideal data setup `title` should contain the well known name of the market as in `Kirchenmarkt Rüppurr` or a type qualifier as in `Trödelmarkt Oberreut`. The `location` field should provide detailed address information as in `Auf dem Julius-Leber-Platz` or `Vor der Christ-König-Kirche`.

**Comment by torfsen** [comment]
I see you point, but on some markets there is simply no difference between these two. Of course I can use a title of `Wochenmarkt Werderplatz` and a location `Auf dem Werderplatz`, but for me that's just clutter compared to simply using a title of `Werderplatz`, in particular since we only cover traditional farmer markets in Karlsruhe.

I like your addition of a validation step, but I do think that we should keep `location` optional.

**Comment by johnjohndoe** [comment]
@torfsen I refactored the validator to differentiate between warnings and errors.

**Comment by johnjohndoe** [comment]
I close this issue since [we decided that the `location` field is optional](https://github.com/wo-ist-markt/wo-ist-markt.github.io/pull/63#discussion_r60352387).
